# wrangler.toml
name = "live-crew-map"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Bind the Durable Object namespace
[[durable_objects.bindings]]
name = "CREW_MAP_ROOM"
class_name = "CrewMapRoom"

[[migrations]]
tag = "v1"
new_classes = [ "CrewMapRoom" ]

